### ISSUE TITLE
Unable to download 0.9.4

### ISSUE THREAD

**Issue by QuattroMusic** [hoffstadt/DearPyGui_Ext#10]
## Version

Operating System: Windows 10

## My Issue

When i try to download the version 0.9.4, it appears the errors on the cmd and instead download the 0.9.3

## To Reproduce

1. open cmd
2. write `pip install dearpygui-ext==0.9.4`

## Screenshot

![image](https://user-images.githubusercontent.com/64004269/167794985-b95eb79f-46bc-453e-9ae5-b64dff2b9f1b.png)

**Comment by hoffstadt** [comment]
Releasing fix now!
